# Generated by Django 3.2.6 on 2023-11-21 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carrera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('standard', 'Standard'), ('student', 'Student')], default='Standard', max_length=15)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carrera.carrera')),
            ],
        ),
    ]
