# Generated by Django 3.2.6 on 2023-11-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materias', '0001_initial'),
        ('carrera', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('standard', 'Standard'), ('student', 'Student'), ('teacher', 'Teacher')], default='Standard', max_length=15)),
                ('verified', models.CharField(choices=[('unverified', 'Unverified'), ('verified', 'Verified')], default='Unverified', max_length=10)),
                ('carreras', models.ManyToManyField(related_name='docentes', to='carrera.Carrera')),
                ('materias', models.ManyToManyField(related_name='docentes', to='materias.Materia')),
            ],
        ),
    ]
